# Estimate molecular evolutionary rate dN/dS and store it in 'dNdS' directory.
library(stringr)
library(ape)

get_newick_value = function(arbre_phylo){ # Function to extract value on terminal branches in a tree.
  nodes <- sapply(arbre_phylo$tip.label,function(x,y) which(y==x),y=arbre_phylo$tip.label)
  edge.length <- setNames(arbre_phylo$edge.length[sapply(nodes,function(x,y) which(y==x),y=arbre_phylo$edge[,2])],names(nodes))
  return(edge.length)
}

list_species = data.frame(sp_taxid = list.dirs("database/BUSCO_annotations/",recursive = F,full.names = F)) # Get species.
list_species$species = sapply(list_species$sp_taxid,function(x) str_split(x,"_NCBI.taxid")[[1]][1]) # Extract scientific name.
list_species$NCBI.taxid = sapply(list_species$sp_taxid,function(x) str_split(x,"_NCBI.taxid")[[1]][2]) # Extract NCBI taxID.
rownames(list_species) = list_species$species

path = "data/dnds_phylo/"

compute_files <- function(name){ # Function to create 2 tree (dN and dS) based on metadata generated by BPP package (see methods). Also generate a summary table.
  concatenate_list = list.files(paste(path,name,"/dnds",sep=""),recursive = T,full.names = F,pattern="raxml.dnd_1") # Collect concatenates.
  concatenate_list = str_replace_all(concatenate_list,"/raxml.dnd_1","")
  
  big_data = data.frame()
  
  concatenate = concatenate_list[1]
  tree = read.tree(paste(path,name,"/dnds/",concatenate,"/raxml.dnd_1",sep="")) # Initialize the tree structure.
  
  dt_per_edge = data.frame(edge.length = tree$edge.length) # Initialize table.
  for (concatenate in concatenate_list){ # For each concatenate calculate the dN and dS by adding the signal of each concatenate.
    tree_length = read.tree(paste(path,name,"/dnds/",concatenate,"/raxml.dnd_1",sep=""))
    for (type in c("dN","dS")){
      for (numden in c("","_norm")){
        tree = read.tree(paste(path,name,"/dnds/",concatenate,"/counts_",type,numden,".dnd",sep="")) # Get original values.
        if (numden == "_norm"){ tree$edge.length = tree$edge.length / tree_length$edge.length} # Calculation of the denominator for dN and dS.
        if (paste(type,numden,sep="") %in% colnames(dt_per_edge)){ # Adding the signal of each concatenate in a table per column.
          dt_per_edge[,paste(type,numden,sep="")] = tree$edge.length + dt_per_edge[,paste(type,numden,sep="")]
        } else {
          dt_per_edge[,paste(type,numden,sep="")] = tree$edge.length 
        }
      }
    }
  }
  
  tree$edge.length = dt_per_edge$dN / dt_per_edge$dN_norm
  write.tree(tree,paste("database/dNdS/newick/",name,"_dN.nwk",sep="")) # Save dN tree.
  
  tree$edge.length = dt_per_edge$dS / dt_per_edge$dS_norm
  write.tree(tree,paste("database/dNdS/newick/",name,"_dS.nwk",sep="")) # Save dS tree.
  
  
  data = data.frame(species = tree$tip.label,
                    NCBI.taxid = list_species[tree$tip.label,]$NCBI.taxid,
                    dN = get_newick_value(read.tree(paste("database/dNdS/newick/",name,"_dN.nwk",sep="")))[tree$tip.label],
                    dS = get_newick_value(read.tree(paste("database/dNdS/newick/",name,"_dS.nwk",sep="")))[tree$tip.label]
  )
  data$dNdS = data$dN / data$dS
  
  write.table(data , paste("database/dNdS/",name,".tab",sep=""),quote=F,row.names = F,sep="\t") # Save summary table.
  file.copy(paste("data/dnds_phylo/",name,"/phylogeny/raxml.root.nwk",sep=""),paste("database/dNdS/phylogeny/",name,"_root.nwk",sep="")) # Copy in the database the phylogenetic tree.
}


compute_files(name = "Eukaryota") # Execute the function for Eukaryota set.
compute_files(name = "Embryophyta") # Execute the function for Embryophyta set.
compute_files(name = "Metazoa") # Execute the function for Metazoa set.
